trigger:
- main

pool:
  name: Default  # self-hosted agent pool name

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '9.0.x'
  displayName: 'Use .NET SDK'

- script: dotnet build --configuration Release
  displayName: 'Build'
  workingDirectory: e2e/e2e/CarvedRock.End2End.Tests
- task: PowerShell@2
  displayName: 'Install Playwright Browsers'
  inputs:
    targetType: inline
    script: ./bin/Debug/net9.0/playwright.ps1 install --with-deps
    workingDirectory: e2e/e2e/CarvedRock.End2End.Tests
- script: dotnet test -s ./.runsettings --configuration Release
  displayName: 'Run Tests'
  workingDirectory: e2e/e2e/CarvedRock.End2End.Tests