name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Build & Install
      working-directory: e2e/e2e
      run: dotnet build
    - name: Ensure browsers are installed
      run: ./e2e/e2e/CarvedRock.End2End.Tests/bin/Debug/net9.0/playwright.sh install --with-deps
    - name: Run your tests
      working-directory: e2e/e2e
      run: dotnet test -s ./aca-firefox.runsettings